package examen2.miguelrojas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menuComputadoras = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        js_tamanoRAM = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        js_tiempoRAM = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_marcaRAM = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        js_tamanoDD = new javax.swing.JSpinner();
        tf_marcaDD = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        js_tiempoDD = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        tf_yearC = new javax.swing.JTextField();
        tf_colorC = new javax.swing.JTextField();
        tf_materialC = new javax.swing.JTextField();
        tf_numeroSerieC = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        js_capacidadBateria = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tf_materialBateria = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        js_tiempoBateria = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_materialTeclado = new javax.swing.JTextField();
        tf_colorTeclado = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        js_tiempoTeclado = new javax.swing.JSpinner();
        jLabel45 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        rb_tactilS = new javax.swing.JRadioButton();
        rb_tactilN = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        tf_tipoPantalla = new javax.swing.JTextField();
        js_tiempoPantalla = new javax.swing.JSpinner();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tf_velocidadProcesador = new javax.swing.JTextField();
        js_numeroNucleos = new javax.swing.JSpinner();
        jLabel43 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        js_tiempoProcesador = new javax.swing.JSpinner();
        jb_crearComputadora = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_listaMod_ElimComputadoras = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jb_eliminarCompu = new javax.swing.JButton();
        jd_menuTecnicos = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jb_crearTecnico = new javax.swing.JButton();
        tf_nombreTecnico = new javax.swing.JTextField();
        js_edad = new javax.swing.JSpinner();
        rb_M = new javax.swing.JRadioButton();
        rb_F = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_listaModElimTecnicos = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jb_modTecnico = new javax.swing.JButton();
        jb_eliminarTecnicos = new javax.swing.JButton();
        bg_genero = new javax.swing.ButtonGroup();
        jd_modTecnico = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jb_modificarTecnico = new javax.swing.JButton();
        rb_modM = new javax.swing.JRadioButton();
        rb_modF = new javax.swing.JRadioButton();
        tf_modNombreT = new javax.swing.JTextField();
        js_edadModT = new javax.swing.JSpinner();
        bg_modGenero = new javax.swing.ButtonGroup();
        bg_tactil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaComputadoras = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listaTecnicos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jb_menuTecnicos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel14.setText("Crear Computadora");

        jLabel15.setText("Numero de Serie:");

        jLabel16.setText("Año:");

        jLabel17.setText("Color:");

        jLabel18.setText("Material:");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("RAM");

        jLabel20.setText("Tamaño:");

        js_tamanoRAM.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel38.setText("Tiempo de Ensamblaje:");

        jLabel44.setText("s");

        jLabel21.setText("Marca:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(js_tamanoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(77, 77, 77)
                                        .addComponent(tf_marcaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(18, 18, 18)
                                        .addComponent(js_tiempoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(js_tamanoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_marcaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(js_tiempoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Disco Duro");

        jLabel23.setText("Tamaño:");

        jLabel24.setText("Marca:");

        jLabel40.setText("Tiempo de Ensamblaje:");

        jLabel49.setText("s");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(js_tiempoDD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_tamanoDD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(js_tiempoDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(js_tamanoDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Bateria");

        jLabel29.setText("Capacidad:");

        jLabel30.setText("hrs");

        jLabel31.setText("Material:");

        jLabel41.setText("Tiempo de Ensamblaje:");

        jLabel47.setText("s");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_tiempoBateria, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(tf_materialBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(js_capacidadBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(js_capacidadBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_materialBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(js_tiempoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setText("Teclado");

        jLabel32.setText("Material:");

        jLabel33.setText("Color:");

        jLabel39.setText("Tiempo de Ensamblaje:");

        jLabel45.setText("s");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_tiempoTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_materialTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_colorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_materialTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_colorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(js_tiempoTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("Pantalla");

        jLabel34.setText("Tactil:");

        bg_tactil.add(rb_tactilS);
        rb_tactilS.setSelected(true);
        rb_tactilS.setText("Si");

        bg_tactil.add(rb_tactilN);
        rb_tactilN.setText("No");

        jLabel35.setText("Tipo:");

        jLabel42.setText("Tiempo de Ensamblaje:");

        jLabel46.setText("s");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(rb_tactilS)
                                .addGap(27, 27, 27)
                                .addComponent(rb_tactilN))
                            .addComponent(tf_tipoPantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(js_tiempoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(rb_tactilS)
                    .addComponent(rb_tactilN))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_tipoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(js_tiempoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("Procesador");

        jLabel36.setText("Numero de Nucleos:");

        jLabel37.setText("Velocidad:");

        jLabel43.setText("Tiempo de Ensamblaje:");

        jLabel48.setText("s");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(js_tiempoProcesador, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_velocidadProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(js_numeroNucleos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_velocidadProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(js_numeroNucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel48)
                    .addComponent(js_tiempoProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jb_crearComputadora.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jb_crearComputadora.setText("Crear");
        jb_crearComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearComputadoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tf_numeroSerieC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(96, 96, 96)
                                .addComponent(tf_yearC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_materialC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_colorC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addComponent(jb_crearComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel14)
                        .addGap(47, 47, 47)
                        .addComponent(tf_yearC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(tf_numeroSerieC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(tf_colorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(tf_materialC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jb_crearComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear [C]", jPanel2);

        jScrollPane3.setViewportView(jl_listaMod_ElimComputadoras);

        jLabel4.setText("Lista de Computadoras");

        jButton4.setText("Modificar");

        jb_eliminarCompu.setText("Eliminar");
        jb_eliminarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarCompuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_eliminarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_eliminarCompu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar/Eliminar [C]", jPanel3);

        javax.swing.GroupLayout jd_menuComputadorasLayout = new javax.swing.GroupLayout(jd_menuComputadoras.getContentPane());
        jd_menuComputadoras.getContentPane().setLayout(jd_menuComputadorasLayout);
        jd_menuComputadorasLayout.setHorizontalGroup(
            jd_menuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuComputadorasLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_menuComputadorasLayout.setVerticalGroup(
            jd_menuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_menuComputadorasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setText("Crear Tecnico");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Edad:");

        jLabel9.setText("Genero:");

        jb_crearTecnico.setText("Crear ");
        jb_crearTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearTecnicoMouseClicked(evt);
            }
        });

        js_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bg_genero.add(rb_M);
        rb_M.setSelected(true);
        rb_M.setText("M");

        bg_genero.add(rb_F);
        rb_F.setText("F");
        rb_F.setRolloverEnabled(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(rb_M)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_F)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_crearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_M)
                    .addComponent(rb_F))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_crearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear [T]", jPanel4);

        jScrollPane4.setViewportView(jl_listaModElimTecnicos);

        jLabel5.setText("Tecnicos");

        jb_modTecnico.setText("Modificar");
        jb_modTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modTecnicoMouseClicked(evt);
            }
        });

        jb_eliminarTecnicos.setText("Eliminar");
        jb_eliminarTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarTecnicosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_modTecnico)
                            .addComponent(jb_eliminarTecnicos))
                        .addGap(50, 50, 50))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jb_modTecnico)
                        .addGap(28, 28, 28)
                        .addComponent(jb_eliminarTecnicos)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modificar_Eliminar [T]", jPanel5);

        javax.swing.GroupLayout jd_menuTecnicosLayout = new javax.swing.GroupLayout(jd_menuTecnicos.getContentPane());
        jd_menuTecnicos.getContentPane().setLayout(jd_menuTecnicosLayout);
        jd_menuTecnicosLayout.setHorizontalGroup(
            jd_menuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        jd_menuTecnicosLayout.setVerticalGroup(
            jd_menuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        jd_modTecnico.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel10.setText("Modificar Tecnico");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Edad:");

        jLabel13.setText("Genero:");

        jb_modificarTecnico.setText("Modificar");
        jb_modificarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarTecnicoMouseClicked(evt);
            }
        });

        bg_modGenero.add(rb_modM);
        rb_modM.setSelected(true);
        rb_modM.setText("M");

        bg_modGenero.add(rb_modF);
        rb_modF.setText("F");

        js_edadModT.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_modNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edadModT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_modificarTecnico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_modM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(rb_modF)))))
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(rb_modM)
                        .addComponent(rb_modF)
                        .addComponent(tf_modNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_modificarTecnico)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(js_edadModT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap(77, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jd_modTecnicoLayout = new javax.swing.GroupLayout(jd_modTecnico.getContentPane());
        jd_modTecnico.getContentPane().setLayout(jd_modTecnicoLayout);
        jd_modTecnicoLayout.setHorizontalGroup(
            jd_modTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_modTecnicoLayout.setVerticalGroup(
            jd_modTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modTecnicoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jl_listaComputadoras);

        jScrollPane2.setViewportView(jl_listaTecnicos);

        jButton1.setText("Menu Computadoras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jb_menuTecnicos.setText("Menu Tecnicos");
        jb_menuTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuTecnicosMouseClicked(evt);
            }
        });

        jButton3.setText("jButton3");

        jLabel1.setText("Examen2_Lab_MiguelRojas");

        jLabel2.setText("Computadoras");

        jLabel3.setText("Tecnicos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jb_menuTecnicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jb_menuTecnicos)
                    .addComponent(jButton3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearTecnicoMouseClicked
        //Crear Tecnico

        String nombre = null;
        int edad = 0;
        String genero = null;
        boolean crear = true;

        //Validar Entradas
        //Nombre
        if (tf_nombreTecnico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuTecnicos, "Falta ingresar el nombre del tecnico.");
            crear = false;
        } else {
            nombre = tf_nombreTecnico.getText();
        }
        //Edad
        if ((int) js_edad.getValue() < 18) {
            JOptionPane.showMessageDialog(jd_menuTecnicos, "Debe ingresar una edad valida [ > 18]");
            crear = false;
        } else {
            edad = (int) js_edad.getValue();
        }

        //Genero
        if (rb_M.isSelected()) {
            genero = "M";
        } else {
            genero = "F";
        }

        if (crear) {
            //Crear Tecnico
            Tecnico t = new Tecnico(nombre, edad, genero);
            //Agregar a lista
            lista_tecnicos.add(t);
            refrescarListasTecnicos();
            JOptionPane.showMessageDialog(jd_menuTecnicos, "Se creo el tecnico exitosamente!!");
            tf_nombreTecnico.setText("");
            js_edad.setValue(0);
            rb_M.setSelected(true);
            rb_F.setSelected(false);
        }

    }//GEN-LAST:event_jb_crearTecnicoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_menuTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuTecnicosMouseClicked
        jd_menuTecnicos.setModal(true);
        jd_menuTecnicos.pack();
        jd_menuTecnicos.setLocationRelativeTo(this);
        jd_menuTecnicos.setVisible(true);
    }//GEN-LAST:event_jb_menuTecnicosMouseClicked

    private void jb_eliminarTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarTecnicosMouseClicked
        //Eliminar Tecnicos
        if (jl_listaModElimTecnicos.getSelectedIndex() >= 0) {

            int resp_elim = JOptionPane.showConfirmDialog(jd_menuTecnicos, "¿Seguro?", "Eliminar Tecnico",
                    JOptionPane.WARNING_MESSAGE);

            if (resp_elim == JOptionPane.YES_OPTION) {
                //Borrar
                int pos_elim = jl_listaModElimTecnicos.getSelectedIndex();
                lista_tecnicos.remove(pos_elim);
                refrescarListasTecnicos();
                JOptionPane.showMessageDialog(jd_menuTecnicos, "Se elimino correctamente el tecnico.");
            }
        } else {
            JOptionPane.showMessageDialog(jd_menuTecnicos, "Debe elegir una opcion valida.");
        }
    }//GEN-LAST:event_jb_eliminarTecnicosMouseClicked

    private void jb_modTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modTecnicoMouseClicked
        //Abrir ventana modificar tecnico
        if (jl_listaModElimTecnicos.getSelectedIndex() >= 0) {

            //Set valores
            tecnico_seleccionado = lista_tecnicos.get(jl_listaModElimTecnicos.getSelectedIndex());
            tf_modNombreT.setText(tecnico_seleccionado.getNombre_tecnico());
            js_edadModT.setValue(tecnico_seleccionado.getEdad_tecnico());

            if (tecnico_seleccionado.getGenero().equals("M")) {
                rb_modM.setSelected(true);
                rb_modF.setSelected(false);
            } else {
                rb_modM.setSelected(false);
                rb_modF.setSelected(true);
            }

            jd_modTecnico.setModal(true);
            jd_modTecnico.pack();
            jd_modTecnico.setLocationRelativeTo(jd_menuTecnicos);
            jd_modTecnico.setAlwaysOnTop(true);
            jd_modTecnico.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jd_menuTecnicos, "Debe elegir una opcion valida.");
        }
    }//GEN-LAST:event_jb_modTecnicoMouseClicked

    private void jb_modificarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarTecnicoMouseClicked
        //Modificar Tecnico
        String nombre_mod = null, generoMod = null;
        int edad_mod = 0;
        boolean mod = true;
        if (tf_modNombreT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modTecnico, "Falta ingresar nombre del tecnico.");
            mod = false;
        } else {
            nombre_mod = tf_modNombreT.getText();
        }

        if ((int) js_edadModT.getValue() < 18) {
            JOptionPane.showMessageDialog(jd_modTecnico, "Debe ingresar una edad valida [ > 18].");
            mod = false;
        } else {
            edad_mod = (int) js_edadModT.getValue();
        }

        if (rb_modM.isSelected()) {
            generoMod = "M";
        } else {
            generoMod = "F";
        }

        if (mod) {
            //Aplicar Modificacion
            tecnico_seleccionado.setNombre_tecnico(nombre_mod);
            tecnico_seleccionado.setEdad_tecnico(edad_mod);
            tecnico_seleccionado.setGenero(generoMod);
            refrescarListasTecnicos();
            JOptionPane.showMessageDialog(jd_modTecnico, "Modificacion exitosa.");
            jd_modTecnico.dispose();

        }
    }//GEN-LAST:event_jb_modificarTecnicoMouseClicked

    private void jb_crearComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearComputadoraMouseClicked
        //Validacion 
        //Objetos Compu
        int numero_serie = 0, year_compu = 0;
        String color_compu = null, material_compu = null;
        //RAM
        int tamano_ram = 0, tiempo_ram = 0;
        String marca_ram = null;
        //DiscoDuro
        int tamano_dd = 0, tiempo_dd = 0;
        String marca_dd = null;
        //Bateria
        int capacidadB = 0, tiempo_b = 0;
        String material_b = null;
        //Teclado
        String material_teclado = null, color_t = null;
        int tiempo_teclado = 0;
        //Pantalla
        String pantalla_tactil = null, tipo_pantalla = null;
        int tiempo_pantalla = 0;
        //Procesador
        int numero_nucleosP = 0, tiempo_procesador = 0;
        double velocidad = 0.0;
        boolean crearCompu = true;

        //Validar Entradas
        //Numero de Serie
        if (tf_numeroSerieC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar numero de serie.");
            crearCompu = false;
        } else {
            numero_serie = Integer.parseInt(tf_numeroSerieC.getText());
        }

        //Año de compu
        if (tf_yearC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el año de la computadora.");
            crearCompu = false;
        } else {
            year_compu = Integer.parseInt(tf_yearC.getText());
        }

        //Color Compu
        if (tf_colorC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el color de la computadora.");
            crearCompu = false;
        } else {
            color_compu = tf_colorC.getText();
        }

        //Material Compu
        if (tf_materialC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el material de la computadora.");
            crearCompu = false;
        } else {
            material_compu = tf_materialC.getText();
        }

        //Validar RAM
        //Tamaño
        if ((int) js_tamanoRAM.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tamaño del RAM.");
            crearCompu = false;
        } else if ((int) js_tamanoRAM.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tamaño del RAM no puede ser < 0.");
            crearCompu = false;
        } else {
            tamano_ram = (int) js_tamanoRAM.getValue();
        }
        //Marca
        if (tf_marcaRAM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar la marca del RAM.");
            crearCompu = false;
        } else {
            marca_ram = tf_marcaRAM.getText();
        }
        //Tiempo Ram
        if ((int) js_tiempoRAM.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje del RAM");
            crearCompu = false;
        } else if ((int) js_tiempoRAM.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje del RAM debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_ram = (int) js_tiempoRAM.getValue();
        }

        //Disco Duro Validar
        //Tamaño
        if ((int) js_tamanoDD.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tamaño del Disco Duro.");
            crearCompu = false;
        } else if ((int) js_tamanoDD.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tamaño del Disco Duro no puede ser < 0.");
            crearCompu = false;
        } else {
            tamano_dd = (int) js_tamanoDD.getValue();
        }
        //Marca
        if (tf_marcaDD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar la marca del Disco Duro.");
            crearCompu = false;
        } else {
            marca_dd = tf_marcaDD.getText();
        }
        //Tiempo Ram
        if ((int) js_tiempoDD.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje del Disco Duro");
            crearCompu = false;
        } else if ((int) js_tiempoDD.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje del Disco Duro debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_dd = (int) js_tiempoDD.getValue();
        }

        //Validar Bateria
        if ((int) js_capacidadBateria.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar la capacidad de la Bateria.");
            crearCompu = false;
        } else if ((int) js_capacidadBateria.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "La capacidad de la bateria debe ser > 0.");
            crearCompu = false;
        } else {
            capacidadB = (int) js_capacidadBateria.getValue();
        }
        //Marca
        if (tf_materialBateria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el material de la Bateria.");
            crearCompu = false;
        } else {
            material_b = tf_materialBateria.getText();
        }
        //Tiempo Bateria
        if ((int) js_tiempoBateria.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje de la Bateria.");
            crearCompu = false;
        } else if ((int) js_tiempoBateria.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje de la Bateria debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_b = (int) js_tiempoBateria.getValue();
        }

        //Validar Teclado
        if (tf_materialTeclado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el material del teclado.");
            crearCompu = false;
        } else {
            material_teclado = tf_materialTeclado.getText();
        }

        //Color Teclado
        if (tf_colorTeclado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el color del teclado.");
            crearCompu = false;
        } else {
            color_t = tf_colorTeclado.getText();
        }

        //Tiempo Teclado
        if ((int) js_tiempoTeclado.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje del teclado.");
            crearCompu = false;
        } else if ((int) js_tiempoTeclado.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje del teclado debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_teclado = (int) js_tiempoTeclado.getValue();
        }

        //Pantalla
        //Tactil
        if (rb_tactilS.isSelected()) {
            pantalla_tactil = "Si";
        } else {
            pantalla_tactil = "No";
        }

        //Tipo
        if (tf_tipoPantalla.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tipo de pantalla.");
            crearCompu = false;
        } else {
            tipo_pantalla = tf_tipoPantalla.getText();
        }

        //Tiempo Pantalla
        if ((int) js_tiempoPantalla.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje de la pantalla.");
            crearCompu = false;
        } else if ((int) js_tiempoPantalla.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje de la pantalla debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_pantalla = (int) js_tiempoPantalla.getValue();
        }

        //Procesador Validar
        //Numero de nucleos
        if ((int) js_numeroNucleos.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar la cantidad de nucleos del procesador.");
            crearCompu = false;
        } else if ((int) js_numeroNucleos.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "La cantidad de nucleso del procesador debe ser > 0.");
            crearCompu = false;
        } else {
            numero_nucleosP = (int) js_numeroNucleos.getValue();
        }
        //Velocidad
        if (tf_velocidadProcesador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar la velocidad el procesador.");
            crearCompu = false;
        } else {
            velocidad = Double.parseDouble(tf_velocidadProcesador.getText());
        }
        //Tiempo Procesador
        if ((int) js_tiempoProcesador.getValue() == 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "Falta ingresar el tiempo de ensamblaje del procesador.");
            crearCompu = false;
        } else if ((int) js_tiempoProcesador.getValue() < 0) {
            JOptionPane.showMessageDialog(jd_menuComputadoras, "El tiempo de ensamblaje del procesador debe ser > 0.");
            crearCompu = false;
        } else {
            tiempo_procesador = (int) js_tiempoProcesador.getValue();
        }
        
        
        if (crearCompu) {
            //Crear Objetos para la computadora
            RAM ram = new RAM(tamano_ram, marca_ram, tiempo_ram);//RAM
            DiscoDuro dd = new DiscoDuro(tamano_dd, marca_dd, tiempo_dd);//Disco Duro
            Bateria bateria = new Bateria(capacidadB, material_b, tiempo_b);//Bateria
            Teclado t = new Teclado(material_teclado, color_t, tiempo_teclado);//Teclado
            Pantalla p = new Pantalla(pantalla_tactil, tipo_pantalla, tiempo_pantalla);//Pantalla
            Procesador proces = new Procesador(numero_nucleosP, velocidad, tiempo_procesador);//Procesador
            
            
            //Crear Computadore
            Computadora c = new Computadora(numero_serie, year_compu, color_compu, material_compu, ram, dd, bateria, t, p, proces);
            //Agregar a lista
            lista_computadoras.add(c);
            
            JOptionPane.showMessageDialog(jd_menuComputadoras,"Se creo la computadora exitosamente!!");
            //RefrescarListas
            //Limpiar Campos
            tf_numeroSerieC.setText("");
            tf_yearC.setText("");
            tf_materialC.setText("");
            tf_colorC.setText("");
            
            js_tamanoRAM.setValue(0);
            tf_marcaRAM.setText("");
            js_tiempoRAM.setValue(0);
            
            js_tamanoDD.setValue(0);
            tf_marcaDD.setText("");
            js_tiempoDD.setValue(0);
            
            js_capacidadBateria.setValue(0);
            tf_materialBateria.setText("");
            js_tiempoBateria.setValue(0);
            
            tf_colorTeclado.setText("");
            tf_materialTeclado.setText("");
            js_tiempoTeclado.setValue(0);
            
            rb_tactilS.setSelected(true);
            rb_tactilN.setSelected(false);
            tf_tipoPantalla.setText("");
            js_tiempoPantalla.setValue(0);
            
            js_numeroNucleos.setValue(0);
            tf_velocidadProcesador.setText("");
            js_tiempoProcesador.setValue(0);
        }
    }//GEN-LAST:event_jb_crearComputadoraMouseClicked

    private void jb_eliminarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarCompuMouseClicked
        //Eliminar Compu
        if (jl_listaMod_ElimComputadoras.getSelectedIndex() >=0) {
            
            int resp_elim = JOptionPane.showConfirmDialog(jd_menuComputadoras,"¿Seguro?", "Eliminar Computadora", 
                    JOptionPane.WARNING_MESSAGE);
            
            if (resp_elim == JOptionPane.YES_OPTION) {
                int pos_elim = jl_listaMod_ElimComputadoras.getSelectedIndex();
                lista_computadoras.remove(pos_elim);
                refrescarListaComputadoras();
            }
        } else {
            JOptionPane.showMessageDialog(jd_menuComputadoras,"Debe elegir una opcion valida.");
        }
    }//GEN-LAST:event_jb_eliminarCompuMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_genero;
    private javax.swing.ButtonGroup bg_modGenero;
    private javax.swing.ButtonGroup bg_tactil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jb_crearComputadora;
    private javax.swing.JButton jb_crearTecnico;
    private javax.swing.JButton jb_eliminarCompu;
    private javax.swing.JButton jb_eliminarTecnicos;
    private javax.swing.JButton jb_menuTecnicos;
    private javax.swing.JButton jb_modTecnico;
    private javax.swing.JButton jb_modificarTecnico;
    private javax.swing.JDialog jd_menuComputadoras;
    private javax.swing.JDialog jd_menuTecnicos;
    private javax.swing.JDialog jd_modTecnico;
    private javax.swing.JList<String> jl_listaComputadoras;
    private javax.swing.JList<Tecnico> jl_listaModElimTecnicos;
    private javax.swing.JList<String> jl_listaMod_ElimComputadoras;
    private javax.swing.JList<String> jl_listaTecnicos;
    private javax.swing.JSpinner js_capacidadBateria;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JSpinner js_edadModT;
    private javax.swing.JSpinner js_numeroNucleos;
    private javax.swing.JSpinner js_tamanoDD;
    private javax.swing.JSpinner js_tamanoRAM;
    private javax.swing.JSpinner js_tiempoBateria;
    private javax.swing.JSpinner js_tiempoDD;
    private javax.swing.JSpinner js_tiempoPantalla;
    private javax.swing.JSpinner js_tiempoProcesador;
    private javax.swing.JSpinner js_tiempoRAM;
    private javax.swing.JSpinner js_tiempoTeclado;
    private javax.swing.JRadioButton rb_F;
    private javax.swing.JRadioButton rb_M;
    private javax.swing.JRadioButton rb_modF;
    private javax.swing.JRadioButton rb_modM;
    private javax.swing.JRadioButton rb_tactilN;
    private javax.swing.JRadioButton rb_tactilS;
    private javax.swing.JTextField tf_colorC;
    private javax.swing.JTextField tf_colorTeclado;
    private javax.swing.JTextField tf_marcaDD;
    private javax.swing.JTextField tf_marcaRAM;
    private javax.swing.JTextField tf_materialBateria;
    private javax.swing.JTextField tf_materialC;
    private javax.swing.JTextField tf_materialTeclado;
    private javax.swing.JTextField tf_modNombreT;
    private javax.swing.JTextField tf_nombreTecnico;
    private javax.swing.JTextField tf_numeroSerieC;
    private javax.swing.JTextField tf_tipoPantalla;
    private javax.swing.JTextField tf_velocidadProcesador;
    private javax.swing.JTextField tf_yearC;
    // End of variables declaration//GEN-END:variables
    ArrayList<Tecnico> lista_tecnicos = new ArrayList();
    ArrayList<Computadora> lista_computadoras = new ArrayList();

    Tecnico tecnico_seleccionado;

    public void refrescarListasTecnicos() {

        DefaultListModel model = new DefaultListModel();

        for (Tecnico t : lista_tecnicos) {
            model.addElement(t);
        }

        jl_listaTecnicos.setModel(model);
        jl_listaModElimTecnicos.setModel(model);
    }
    
    public void refrescarListaComputadoras(){
        
        DefaultListModel model = new DefaultListModel();
        
        for (Computadora c : lista_computadoras) {
            model.addElement(c);
        }
        
        jl_listaComputadoras.setModel(model);
        jl_listaMod_ElimComputadoras.setModel(model);
    }
}
